import type { Metadata } from "next";
import Sidebar from "../components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex relative">
      <Sidebar />
      <main className="md:flex-1 h-screen w-[calc(100vw-408px-344px)] relative">
        {children}
      </main>
    </div>
  );
}
